<?php
/**
 * @file
 * Code for the Field image tooltips feature.
 */

include_once 'field_image_tooltips.features.inc';

/**
 * Implements hook_help().
 */
function field_image_tooltips_help($path, $arg) {
  switch ($path) {
    case 'admin/help#field_image_tooltips':
      $output = file_get_contents(drupal_get_path('module', 'field_image_tooltips') . '/README.txt');
      return module_exists('markdown') ? filter_xss_admin(module_invoke('markdown', 'filter', 'process', 0, -1, $output)) : '<pre>' . check_plain($output) . '</pre>';
  }
}
